export const MEMBERS = {
  // 1期
  '秋元真夏':             { gen: 1, active: false },
  '安藤美雲':             { gen: 1, active: false },
  '生田絵梨花':           { gen: 1, active: false },
  '生駒里奈':             { gen: 1, active: false },
  '市來玲奈':             { gen: 1, active: false },
  '伊藤かりん':           { gen: 1, active: false },
  '伊藤寧寧':             { gen: 1, active: false },
  '伊藤萬理華':           { gen: 1, active: false },
  '岩瀬佑美子':           { gen: 1, active: false },
  '衛藤美彩':             { gen: 1, active: false },
  '大和里菜':             { gen: 1, active: false },
  '川後陽菜':             { gen: 1, active: false },
  '川村真洋':             { gen: 1, active: false },
  '柏幸奈':               { gen: 1, active: false },
  '斉藤優里':             { gen: 1, active: false },
  '齋藤飛鳥':             { gen: 1, active: false },
  '桜井玲香':             { gen: 1, active: false },
  '相楽伊織':             { gen: 1, active: false },
  '白石麻衣':             { gen: 1, active: false },
  '高山一実':             { gen: 1, active: false },
  '中元日芽香':           { gen: 1, active: false },
  '能條愛未':             { gen: 1, active: false },
  '永島聖羅':             { gen: 1, active: false },
  '西野七瀬':             { gen: 1, active: false },
  '橋本奈々未':           { gen: 1, active: false },
  '畠中清羅':             { gen: 1, active: false },
  '樋口日奈':             { gen: 1, active: false },
  '深川麻衣':             { gen: 1, active: false },
  '星野みなみ':           { gen: 1, active: false },
  '松井玲奈':             { gen: 1, active: false },
  '松村沙友理':           { gen: 1, active: false },
  '宮澤成良':             { gen: 1, active: false },
  '山本穂乃香':           { gen: 1, active: false },
  '若月佑美':             { gen: 1, active: false },
  '和田まあや':           { gen: 1, active: false },
  '吉本彩華':             { gen: 1, active: false },
  // 2期
  '井上小百合':           { gen: 2, active: false },
  '伊藤純奈':             { gen: 2, active: false },
  '斎藤ちはる':           { gen: 2, active: false },
  '佐々木琴子':           { gen: 2, active: false },
  '新内眞衣':             { gen: 2, active: false },
  '鈴木絢音':             { gen: 2, active: false },
  '寺田蘭世':             { gen: 2, active: false },
  '中田花奈':             { gen: 2, active: false },
  '堀未央奈':             { gen: 2, active: false },
  '北野日奈子':           { gen: 2, active: false },
  '渡辺みり愛':           { gen: 2, active: false },
  // 3期
  '伊藤理々杏':           { gen: 3, active: true },
  '岩本蓮加':             { gen: 3, active: true },
  '吉田綾乃クリスティー': { gen: 3, active: true },
  '梅澤美波':             { gen: 3, active: false },
  '大園桃子':             { gen: 3, active: false },
  '久保史緒里':           { gen: 3, active: false },
  '阪口珠美':             { gen: 3, active: false },
  '佐藤楓':               { gen: 3, active: false },
  '中村麗乃':             { gen: 3, active: false },
  '向井葉月':             { gen: 3, active: false },
  '山崎怜奈':             { gen: 3, active: false },
  '山下美月':             { gen: 3, active: false },
  '与田祐希':             { gen: 3, active: false },
  // 4期
  '遠藤さくら':           { gen: 4, active: true },
  '賀喜遥香':             { gen: 4, active: true },
  '金川紗耶':             { gen: 4, active: true },
  '黒見明香':             { gen: 4, active: true },
  '柴田柚菜':             { gen: 4, active: true },
  '田村真佑':             { gen: 4, active: true },
  '筒井あやめ':           { gen: 4, active: true },
  '林瑠奈':               { gen: 4, active: true },
  '弓木奈於':             { gen: 4, active: true },
  '掛橋沙耶香':           { gen: 4, active: false },
  '北川悠理':             { gen: 4, active: false },
  '清宮レイ':             { gen: 4, active: false },
  '早川聖来':             { gen: 4, active: false },
  '松尾美佑':             { gen: 4, active: false },
  '矢久保美緒':           { gen: 4, active: false },
  '佐藤璃果':             { gen: 4, active: false },
  // 5期
  '五百城茉央':           { gen: 5, active: true },
  '池田瑛紗':             { gen: 5, active: true },
  '一ノ瀬美空':           { gen: 5, active: true },
  '井上和':               { gen: 5, active: true },
  '岡本姫奈':             { gen: 5, active: true },
  '小川彩':               { gen: 5, active: true },
  '奥田いろは':           { gen: 5, active: true },
  '川﨑桜':               { gen: 5, active: true },
  '菅原咲月':             { gen: 5, active: true },
  '冨里奈央':             { gen: 5, active: true },
  '中西アルノ':           { gen: 5, active: true },
  // 6期
  '愛宕心響':             { gen: 6, active: true },
  '大越ひなの':           { gen: 6, active: true },
  '小津玲奈':             { gen: 6, active: true },
  '海邉朱莉':             { gen: 6, active: true },
  '川端晃菜':             { gen: 6, active: true },
  '鈴木佑捺':             { gen: 6, active: true },
  '瀬戸口心月':           { gen: 6, active: true },
  '長嶋凛桜':             { gen: 6, active: true },
  '増田三莉音':           { gen: 6, active: true },
  '森平麗心':             { gen: 6, active: true },
  '矢田萌華':             { gen: 6, active: true },
}

export function sortMembersByGen(names) {
  return [...names].sort((a, b) => {
    const ga = MEMBERS[a]?.gen ?? 99
    const gb = MEMBERS[b]?.gen ?? 99
    if (ga !== gb) return ga - gb
    return a.localeCompare(b, 'ja')
  })
}
