export const MEMBERS = {
  // 1期
  '秋元真夏':             { gen: 1, active: false, group: 'nogizaka46' },
  '安藤美雲':             { gen: 1, active: false, group: 'nogizaka46' },
  '生田絵梨花':           { gen: 1, active: false, group: 'nogizaka46' },
  '生駒里奈':             { gen: 1, active: false, group: 'nogizaka46' },
  '市來玲奈':             { gen: 1, active: false, group: 'nogizaka46' },
  '伊藤かりん':           { gen: 1, active: false, group: 'nogizaka46' },
  '伊藤寧寧':             { gen: 1, active: false, group: 'nogizaka46' },
  '伊藤萬理華':           { gen: 1, active: false, group: 'nogizaka46' },
  '井上小百合':           { gen: 1, active: false, group: 'nogizaka46' },
  '岩瀬佑美子':           { gen: 1, active: false, group: 'nogizaka46' },
  '衛藤美彩':             { gen: 1, active: false, group: 'nogizaka46' },
  '川後陽菜':             { gen: 1, active: false, group: 'nogizaka46' },
  '川村真洋':             { gen: 1, active: false, group: 'nogizaka46' },
  '柏幸奈':               { gen: 1, active: false, group: 'nogizaka46' },
  '斉藤優里':             { gen: 1, active: false, group: 'nogizaka46' },
  '齋藤飛鳥':             { gen: 1, active: false, group: 'nogizaka46' },
  '斎藤ちはる':           { gen: 1, active: false, group: 'nogizaka46' },
  '桜井玲香':             { gen: 1, active: false, group: 'nogizaka46' },
  '相楽伊織':             { gen: 1, active: false, group: 'nogizaka46' },
  '白石麻衣':             { gen: 1, active: false, group: 'nogizaka46' },
  '高山一実':             { gen: 1, active: false, group: 'nogizaka46' },
  '中田花奈':             { gen: 1, active: false, group: 'nogizaka46' },
  '中元日芽香':           { gen: 1, active: false, group: 'nogizaka46' },
  '能條愛未':             { gen: 1, active: false, group: 'nogizaka46' },
  '永島聖羅':             { gen: 1, active: false, group: 'nogizaka46' },
  '西野七瀬':             { gen: 1, active: false, group: 'nogizaka46' },
  '橋本奈々未':           { gen: 1, active: false, group: 'nogizaka46' },
  '畠中清羅':             { gen: 1, active: false, group: 'nogizaka46' },
  '樋口日奈':             { gen: 1, active: false, group: 'nogizaka46' },
  '深川麻衣':             { gen: 1, active: false, group: 'nogizaka46' },
  '星野みなみ':           { gen: 1, active: false, group: 'nogizaka46' },
  '松井玲奈':             { gen: 1, active: false, group: 'nogizaka46' },
  '松村沙友理':           { gen: 1, active: false, group: 'nogizaka46' },
  '宮澤成良':             { gen: 1, active: false, group: 'nogizaka46' },
  '大和里菜':             { gen: 1, active: false, group: 'nogizaka46' },
  '山本穂乃香':           { gen: 1, active: false, group: 'nogizaka46' },
  '吉本彩華':             { gen: 1, active: false, group: 'nogizaka46' },
  '若月佑美':             { gen: 1, active: false, group: 'nogizaka46' },
  '和田まあや':           { gen: 1, active: false, group: 'nogizaka46' },
  // 2期
  '伊藤純奈':             { gen: 2, active: false, group: 'nogizaka46' },
  '北野日奈子':           { gen: 2, active: false, group: 'nogizaka46' },
  '佐々木琴子':           { gen: 2, active: false, group: 'nogizaka46' },
  '新内眞衣':             { gen: 2, active: false, group: 'nogizaka46' },
  '鈴木絢音':             { gen: 2, active: false, group: 'nogizaka46' },
  '寺田蘭世':             { gen: 2, active: false, group: 'nogizaka46' },
  '堀未央奈':             { gen: 2, active: false, group: 'nogizaka46' },
  '山崎怜奈':             { gen: 2, active: false, group: 'nogizaka46' },
  '渡辺みり愛':           { gen: 2, active: false, group: 'nogizaka46' },
  // 3期
  '伊藤理々杏':           { gen: 3, active: true, group: 'nogizaka46' },
  '岩本蓮加':             { gen: 3, active: true, group: 'nogizaka46' },
  '梅澤美波':             { gen: 3, active: false, group: 'nogizaka46' },
  '大園桃子':             { gen: 3, active: false, group: 'nogizaka46' },
  '久保史緒里':           { gen: 3, active: false, group: 'nogizaka46' },
  '阪口珠美':             { gen: 3, active: false, group: 'nogizaka46' },
  '佐藤楓':               { gen: 3, active: false, group: 'nogizaka46' },
  '中村麗乃':             { gen: 3, active: false, group: 'nogizaka46' },
  '向井葉月':             { gen: 3, active: false, group: 'nogizaka46' },
  '山下美月':             { gen: 3, active: false, group: 'nogizaka46' },
  '吉田綾乃クリスティー': { gen: 3, active: true, group: 'nogizaka46' },
  '与田祐希':             { gen: 3, active: false, group: 'nogizaka46' },
  // 4期
  '遠藤さくら':           { gen: 4, active: true, group: 'nogizaka46' },
  '賀喜遥香':             { gen: 4, active: true, group: 'nogizaka46' },
  '掛橋沙耶香':           { gen: 4, active: false, group: 'nogizaka46' },
  '金川紗耶':             { gen: 4, active: true, group: 'nogizaka46' },
  '北川悠理':             { gen: 4, active: false, group: 'nogizaka46' },
  '黒見明香':             { gen: 4, active: true, group: 'nogizaka46' },
  '佐藤璃果':             { gen: 4, active: false, group: 'nogizaka46' },
  '柴田柚菜':             { gen: 4, active: true, group: 'nogizaka46' },
  '清宮レイ':             { gen: 4, active: false, group: 'nogizaka46' },
  '田村真佑':             { gen: 4, active: true, group: 'nogizaka46' },
  '筒井あやめ':           { gen: 4, active: true, group: 'nogizaka46' },
  '早川聖来':             { gen: 4, active: false, group: 'nogizaka46' },
  '林瑠奈':               { gen: 4, active: true, group: 'nogizaka46' },
  '松尾美佑':             { gen: 4, active: false, group: 'nogizaka46' },
  '矢久保美緒':           { gen: 4, active: false, group: 'nogizaka46' },
  '弓木奈於':             { gen: 4, active: true, group: 'nogizaka46' },
  // 5期
  '五百城茉央':           { gen: 5, active: true, group: 'nogizaka46' },
  '池田瑛紗':             { gen: 5, active: true, group: 'nogizaka46' },
  '一ノ瀬美空':           { gen: 5, active: true, group: 'nogizaka46' },
  '井上和':               { gen: 5, active: true, group: 'nogizaka46' },
  '岡本姫奈':             { gen: 5, active: true, group: 'nogizaka46' },
  '小川彩':               { gen: 5, active: true, group: 'nogizaka46' },
  '奥田いろは':           { gen: 5, active: true, group: 'nogizaka46' },
  '川﨑桜':               { gen: 5, active: true, group: 'nogizaka46' },
  '菅原咲月':             { gen: 5, active: true, group: 'nogizaka46' },
  '冨里奈央':             { gen: 5, active: true, group: 'nogizaka46' },
  '中西アルノ':           { gen: 5, active: true, group: 'nogizaka46' },
  // 6期
  '愛宕心響':             { gen: 6, active: true, group: 'nogizaka46' },
  '大越ひなの':           { gen: 6, active: true, group: 'nogizaka46' },
  '小津玲奈':             { gen: 6, active: true, group: 'nogizaka46' },
  '海邉朱莉':             { gen: 6, active: true, group: 'nogizaka46' },
  '川端晃菜':             { gen: 6, active: true, group: 'nogizaka46' },
  '鈴木佑捺':             { gen: 6, active: true, group: 'nogizaka46' },
  '瀬戸口心月':           { gen: 6, active: true, group: 'nogizaka46' },
  '長嶋凛桜':             { gen: 6, active: true, group: 'nogizaka46' },
  '増田三莉音':           { gen: 6, active: true, group: 'nogizaka46' },
  '森平麗心':             { gen: 6, active: true, group: 'nogizaka46' },
  '矢田萌華':             { gen: 6, active: true, group: 'nogizaka46' },
  // ── 櫻坂46 ──────────────────────────────────────────────
  // 1期
  '石森虹花':   { gen: 11, active: false, group: 'sakurazaka46' },
  '今泉佑唯':   { gen: 11, active: false, group: 'sakurazaka46' },
  '上村莉菜':   { gen: 11, active: false, group: 'sakurazaka46' },
  '尾関梨香':   { gen: 11, active: false, group: 'sakurazaka46' },
  '織田奈那':   { gen: 11, active: false, group: 'sakurazaka46' },
  '小池美波':   { gen: 11, active: false, group: 'sakurazaka46' },
  '小林由依':   { gen: 11, active: false, group: 'sakurazaka46' },
  '齋藤冬優花': { gen: 11, active: false, group: 'sakurazaka46' },
  '佐藤詩織':   { gen: 11, active: false, group: 'sakurazaka46' },
  '志田愛佳':   { gen: 11, active: false, group: 'sakurazaka46' },
  '菅井友香':   { gen: 11, active: false, group: 'sakurazaka46' },
  '鈴木泉帆':   { gen: 11, active: false, group: 'sakurazaka46' },
  '鈴本美愉':   { gen: 11, active: false, group: 'sakurazaka46' },
  '長沢菜々香': { gen: 11, active: false, group: 'sakurazaka46' },
  '長濱ねる':   { gen: 11, active: false, group: 'sakurazaka46' },
  '土生瑞穂':   { gen: 11, active: false, group: 'sakurazaka46' },
  '原田葵':     { gen: 11, active: false, group: 'sakurazaka46' },
  '原田まゆ':   { gen: 11, active: false, group: 'sakurazaka46' },
  '平手友梨奈': { gen: 11, active: false, group: 'sakurazaka46' },
  '守屋茜':     { gen: 11, active: false, group: 'sakurazaka46' },
  '米谷奈々未': { gen: 11, active: false, group: 'sakurazaka46' },
  '渡辺梨加':   { gen: 11, active: false, group: 'sakurazaka46' },
  '渡邉理佐':   { gen: 11, active: false, group: 'sakurazaka46' },
  // 2期（現役＋畢業混排）
  '井上梨名':   { gen: 12, active: false, group: 'sakurazaka46' },
  '遠藤光莉':   { gen: 12, active: true, group: 'sakurazaka46' },
  '大園玲':     { gen: 12, active: true, group: 'sakurazaka46' },
  '大沼晶保':   { gen: 12, active: true, group: 'sakurazaka46' },
  '幸阪茉里乃': { gen: 12, active: true, group: 'sakurazaka46' },
  '関有美子':   { gen: 12, active: false, group: 'sakurazaka46' },
  '武元唯衣':   { gen: 12, active: false, group: 'sakurazaka46' },
  '田村保乃':   { gen: 12, active: true, group: 'sakurazaka46' },
  '藤吉夏鈴':   { gen: 12, active: true, group: 'sakurazaka46' },
  '増本綺良':   { gen: 12, active: true, group: 'sakurazaka46' },
  '松平璃子':   { gen: 12, active: false, group: 'sakurazaka46' },
  '松田里奈':   { gen: 12, active: true, group: 'sakurazaka46' },
  '森田ひかる': { gen: 12, active: true, group: 'sakurazaka46' },
  '守屋麗奈':   { gen: 12, active: true, group: 'sakurazaka46' },
  '山﨑天':     { gen: 12, active: true, group: 'sakurazaka46' },
  // 3期
  '石森璃花':   { gen: 13, active: true, group: 'sakurazaka46' },
  '遠藤理子':   { gen: 13, active: true, group: 'sakurazaka46' },
  '小田倉麗奈': { gen: 13, active: true, group: 'sakurazaka46' },
  '小島凪紗':   { gen: 13, active: true, group: 'sakurazaka46' },
  '谷口愛季':   { gen: 13, active: true, group: 'sakurazaka46' },
  '中嶋優月':   { gen: 13, active: true, group: 'sakurazaka46' },
  '的野美青':   { gen: 13, active: true, group: 'sakurazaka46' },
  '向井純葉':   { gen: 13, active: true, group: 'sakurazaka46' },
  '村井優':     { gen: 13, active: true, group: 'sakurazaka46' },
  '村山美羽':   { gen: 13, active: true, group: 'sakurazaka46' },
  '山下瞳月':   { gen: 13, active: true, group: 'sakurazaka46' },
  // 4期
  '浅井恋乃未': { gen: 14, active: true, group: 'sakurazaka46' },
  '稲熊ひな':   { gen: 14, active: true, group: 'sakurazaka46' },
  '勝又春':     { gen: 14, active: true, group: 'sakurazaka46' },
  '佐藤愛桜':   { gen: 14, active: true, group: 'sakurazaka46' },
  '中川智尋':   { gen: 14, active: true, group: 'sakurazaka46' },
  '松本和子':   { gen: 14, active: true, group: 'sakurazaka46' },
  '目黒陽色':   { gen: 14, active: true, group: 'sakurazaka46' },
  '山川宇衣':   { gen: 14, active: true, group: 'sakurazaka46' },
  '山田桃実':   { gen: 14, active: true, group: 'sakurazaka46' },
  // ── 日向坂46 ──────────────────────────────────────────────
  // 1期
  '井口眞緒':   { gen: 21, active: false, group: 'hinatazaka46' },
  '潮紗理菜':   { gen: 21, active: false, group: 'hinatazaka46' },
  '柿崎芽実':   { gen: 21, active: false, group: 'hinatazaka46' },
  '影山優佳':   { gen: 21, active: false, group: 'hinatazaka46' },
  '加藤史帆':   { gen: 21, active: false, group: 'hinatazaka46' },
  '齊藤京子':   { gen: 21, active: false, group: 'hinatazaka46' },
  '佐々木久美': { gen: 21, active: false, group: 'hinatazaka46' },
  '佐々木美玲': { gen: 21, active: false, group: 'hinatazaka46' },
  '高瀬愛奈':   { gen: 21, active: false, group: 'hinatazaka46' },
  '高本彩花':   { gen: 21, active: false, group: 'hinatazaka46' },
  '東村芽依':   { gen: 21, active: false, group: 'hinatazaka46' },
  // 2期（現役＋畢業混排）
  '金村美玖':   { gen: 22, active: true, group: 'hinatazaka46' },
  '河田陽菜':   { gen: 22, active: false, group: 'hinatazaka46' },
  '小坂菜緒':   { gen: 22, active: true, group: 'hinatazaka46' },
  '富田鈴花':   { gen: 22, active: false, group: 'hinatazaka46' },
  '丹生明里':   { gen: 22, active: false, group: 'hinatazaka46' },
  '濱岸ひより': { gen: 22, active: false, group: 'hinatazaka46' },
  '松田好花':   { gen: 22, active: false, group: 'hinatazaka46' },
  '宮田愛萌':   { gen: 22, active: false, group: 'hinatazaka46' },
  '渡邉美穂':   { gen: 22, active: false, group: 'hinatazaka46' },
  // 3期
  '上村ひなの': { gen: 23, active: true, group: 'hinatazaka46' },
  '髙橋未来虹': { gen: 23, active: true, group: 'hinatazaka46' },
  '森本茉莉':   { gen: 23, active: true, group: 'hinatazaka46' },
  '山口陽世':   { gen: 23, active: true, group: 'hinatazaka46' },
  // 4期（現役＋畢業混排）
  '石塚瑶季':   { gen: 24, active: true, group: 'hinatazaka46' },
  '岸帆夏':     { gen: 24, active: false, group: 'hinatazaka46' },
  '小西夏菜実': { gen: 24, active: true, group: 'hinatazaka46' },
  '清水理央':   { gen: 24, active: true, group: 'hinatazaka46' },
  '正源司陽子': { gen: 24, active: true, group: 'hinatazaka46' },
  '竹内希来里': { gen: 24, active: true, group: 'hinatazaka46' },
  '平尾帆夏':   { gen: 24, active: true, group: 'hinatazaka46' },
  '平岡海月':   { gen: 24, active: true, group: 'hinatazaka46' },
  '藤嶌果歩':   { gen: 24, active: true, group: 'hinatazaka46' },
  '宮地すみれ': { gen: 24, active: true, group: 'hinatazaka46' },
  '山下葉留花': { gen: 24, active: true, group: 'hinatazaka46' },
  '渡辺莉奈':   { gen: 24, active: true, group: 'hinatazaka46' },
  // 5期
  '大田美月':   { gen: 25, active: true, group: 'hinatazaka46' },
  '大野愛実':   { gen: 25, active: true, group: 'hinatazaka46' },
  '片山紗希':   { gen: 25, active: true, group: 'hinatazaka46' },
  '蔵盛妃那乃': { gen: 25, active: true, group: 'hinatazaka46' },
  '坂井新奈':   { gen: 25, active: true, group: 'hinatazaka46' },
  '佐藤優羽':   { gen: 25, active: true, group: 'hinatazaka46' },
  '下田衣珠季': { gen: 25, active: true, group: 'hinatazaka46' },
  '高井俐香':   { gen: 25, active: true, group: 'hinatazaka46' },
  '鶴崎仁香':   { gen: 25, active: true, group: 'hinatazaka46' },
  '松尾桜':     { gen: 25, active: true, group: 'hinatazaka46' },
}

export function getMemberInfo(name) {
  return MEMBERS[name] ?? MEMBERS[name.replace(/　/g, '')] ?? {}
}

// MEMBERS 物件裡的宣告順序本身就是人工校對過的正確五十音順（同期別內），
// 漢字沒有標準讀音資訊，JS 的 localeCompare('ja') 對漢字排出來的順序其實是
// Unicode/筆畫序，不是真正的日文姓名讀音順，所以改用宣告順序的索引來排，
// 不再用 localeCompare 比較漢字本身
const MEMBER_ORDER = new Map(Object.keys(MEMBERS).map((name, i) => [name, i]))

export function memberOrderIndex(name) {
  return MEMBER_ORDER.get(name) ?? MEMBER_ORDER.get(name.replace(/　/g, '')) ?? Infinity
}

const GROUP_ORDER = { nogizaka46: 0, sakurazaka46: 1, hinatazaka46: 2 }

// 以 group 欄位為主排序（乃木坂→櫻坂→日向坂），group 內再按 gen 排
// entries: Array of { name: string, group: string }
export function sortMembersByGroupAndGen(entries) {
  return [...entries].sort((a, b) => {
    const gd = (GROUP_ORDER[a.group] ?? 9) - (GROUP_ORDER[b.group] ?? 9)
    if (gd !== 0) return gd
    const ga = getMemberInfo(a.name).gen ?? 99
    const gb = getMemberInfo(b.name).gen ?? 99
    if (ga !== gb) return ga - gb
    return memberOrderIndex(a.name) - memberOrderIndex(b.name)
  })
}
